# Generated by Django 4.2.2 on 2023-06-16 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=30, unique=True)),
                ('vehicle_sn', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_title', models.CharField(max_length=50)),
                ('issue', models.TextField(max_length=500)),
                ('repairs_made', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('broken_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.vehicle', to_field='vehicle_id')),
            ],
        ),
    ]
